version: '2.1'

services:
  mongodb:
    extends:
      file: common.yml
      service: mongodb

  api:
    extends:
      file: common.yml
      service: api
    links:
      - mongodb
    depends_on:
      - mongodb

  tests:
    container_name: tests
    build: .
    volumes:
      - ./:/home/nodejs/app
    environment:
      MONGO_CONNECTION_STRING: "mongodb://mongodb:${MONGODB_EXPOSED_PORT}/${MONGODB_APPLICATION_DATABASE}"
      TEST_MONGO_CONNECTION_STRING: "mongodb://mongodb:${MONGODB_EXPOSED_PORT}/test"
      NODE_ENV: "test"
      LOG_DISABLE: 1 # this option disables log for test env
    depends_on:
      api:
        condition: service_started
    links:
      - api
      - mongodb
    command: yarn run test

volumes:
  mongostorage: {}
